dubbo:
  application:
    name: dubbo-anno-service-consumer
    qos-enable: true
    qos-port: 44444
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: tri
    port: -1
    ext-protocol: dubbo
server:
  port: 8002